services:
  blackbox-proxy:
    image: node:20
    container_name: blackbox-proxy
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules # node_modules はコンテナ内で管理
    ports:
      - "${PORT}:${PORT}"
    # 初期設定も含めて実行
    command: bash -c "npm install -g typescript tsc-alias && npm i && npm run build && npm run start"
    restart: always

  cloudflared:
    image: cloudflare/cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
    network_mode: service:blackbox-proxy
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
      - TUNNEL_TRANSPORT_PROTOCOL=http2
    restart: always
